package com.jeta.abeille.common;

import com.jeta.foundation.utils.TSUtils;

/**
 * Abeille.java is an automatically generated java file. If you want to make
 * changes, you must edit the Abeille.txt file. The build script will read the
 * file and generate the corresponding Java File
 * 
 * Some global constants and declarations for this application.
 */
public class Abeille {

	/**
	 * @return a version string for the application
	 */
	public static String getVersion() {
		StringBuffer buffer = new StringBuffer();
		// buffer.append( "Beta " );
		buffer.append(MAJOR_VERSION);
		buffer.append(".");
		buffer.append(MINOR_VERSION);
		buffer.append(".");
		buffer.append(SUBMINOR_VERSION);

		if (TSUtils.isDebug()) {
			buffer.append(" (debug) ");

			buffer.append("build (");
			buffer.append(BUILD_NUMBER);
			buffer.append(") ");
			buffer.append(BUILD_DATE);
		}
		return buffer.toString();
	}

	/**
	 * @return a version string for the application
	 */
	public static String getVersionEx() {
		StringBuffer buffer = new StringBuffer();
		// buffer.append( "Beta " );
		buffer.append(MAJOR_VERSION);
		buffer.append(".");
		buffer.append(MINOR_VERSION);
		buffer.append(".");
		buffer.append(SUBMINOR_VERSION);
		buffer.append(" (build ");
		buffer.append(BUILD_NUMBER);
		buffer.append(") ");
		buffer.append(BUILD_DATE);
		return buffer.toString();
	}

	/* do not add anything below this line - auto generated by build script */

	public static int MAJOR_VERSION = 2;
	public static int MINOR_VERSION = 0;
	public static int SUBMINOR_VERSION = 0;
	public static int BUILD_NUMBER = 101;
	public static String DATE_FORMAT = "MM-dd-yyyy HH:mm:ss";
	public static String BUILD_DATE = "03-01-2005 20:16:08";

}