/* Generated By:JavaCC: Do not edit this line. InputParserConstants.java */
package com.jeta.abeille.parsers;

public interface InputParserConstants {

	int EOF = 0;
	int EOL = 4;
	int AND = 5;
	int OR = 6;
	int INTEGER_LITERAL = 7;
	int FLOATING_POINT_LITERAL = 8;
	int EXPONENT = 9;
	int STRING_LITERAL = 10;
	int ID = 11;
	int LETTER = 12;
	int DIGIT = 13;
	int COMMA = 14;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"", "\"and\"", "\"or\"",
			"<INTEGER_LITERAL>", "<FLOATING_POINT_LITERAL>", "<EXPONENT>", "<STRING_LITERAL>", "<ID>", "<LETTER>",
			"<DIGIT>", "\",\"", };

}
