/* Generated By:JavaCC: Do not edit this line. DateMaskParserConstants.java */
package com.jeta.foundation.gui.components.datetime;

public interface DateMaskParserConstants {

	int EOF = 0;
	int EOL = 1;
	int yyyy = 2;
	int MM = 3;
	int MMM = 4;
	int dd = 5;
	int ANY2 = 6;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\"\\n\"", "\"yyyy\"", "\"MM\"", "\"MMM\"", "\"dd\"", "<ANY2>", };

}
