/* Generated By:JavaCC: Do not edit this line. TimeMaskParserConstants.java */
package com.jeta.foundation.gui.components.datetime;

public interface TimeMaskParserConstants {

	int EOF = 0;
	int EOL = 1;
	int hh = 2;
	int HH = 3;
	int mm = 4;
	int ss = 5;
	int a = 6;
	int ANY2 = 7;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\"\\n\"", "\"hh\"", "\"HH\"", "\"mm\"", "\"ss\"", "\"a\"", "<ANY2>", };

}
