/* Generated By:JavaCC: Do not edit this line. MySQLForeignKeyParserTokenManager.java */
package com.jeta.plugins.abeille.mysql.parsers;

import java.util.Collection;
import java.util.ArrayList;

public class MySQLForeignKeyParserTokenManager implements MySQLForeignKeyParserConstants {
	public java.io.PrintStream debugStream = System.out;

	public void setDebugStream(java.io.PrintStream ds) {
		debugStream = ds;
	}

	private final int jjStopStringLiteralDfa_0(int pos, long active0) {
		switch (pos) {
		case 0:
			if ((active0 & 0xfe0L) != 0L) {
				jjmatchedKind = 16;
				return 29;
			}
			return -1;
		case 1:
			if ((active0 & 0xfe0L) != 0L) {
				jjmatchedKind = 16;
				jjmatchedPos = 1;
				return 29;
			}
			return -1;
		case 2:
			if ((active0 & 0x4c0L) != 0L) {
				if (jjmatchedPos < 1) {
					jjmatchedKind = 16;
					jjmatchedPos = 1;
				}
				return -1;
			}
			if ((active0 & 0xb20L) != 0L) {
				jjmatchedKind = 16;
				jjmatchedPos = 2;
				return 29;
			}
			return -1;
		case 3:
			if ((active0 & 0x920L) != 0L) {
				jjmatchedKind = 16;
				jjmatchedPos = 3;
				return 29;
			}
			if ((active0 & 0x200L) != 0L) {
				if (jjmatchedPos < 2) {
					jjmatchedKind = 16;
					jjmatchedPos = 2;
				}
				return -1;
			}
			if ((active0 & 0x4c0L) != 0L) {
				if (jjmatchedPos < 1) {
					jjmatchedKind = 16;
					jjmatchedPos = 1;
				}
				return -1;
			}
			return -1;
		case 4:
			if ((active0 & 0x900L) != 0L) {
				jjmatchedKind = 16;
				jjmatchedPos = 4;
				return 29;
			}
			if ((active0 & 0x200L) != 0L) {
				if (jjmatchedPos < 2) {
					jjmatchedKind = 16;
					jjmatchedPos = 2;
				}
				return -1;
			}
			if ((active0 & 0x4c0L) != 0L) {
				if (jjmatchedPos < 1) {
					jjmatchedKind = 16;
					jjmatchedPos = 1;
				}
				return -1;
			}
			if ((active0 & 0x20L) != 0L)
				return 29;
			return -1;
		case 5:
			if ((active0 & 0x200L) != 0L) {
				if (jjmatchedPos < 2) {
					jjmatchedKind = 16;
					jjmatchedPos = 2;
				}
				return -1;
			}
			if ((active0 & 0x4c0L) != 0L) {
				if (jjmatchedPos < 1) {
					jjmatchedKind = 16;
					jjmatchedPos = 1;
				}
				return -1;
			}
			if ((active0 & 0x900L) != 0L) {
				jjmatchedKind = 16;
				jjmatchedPos = 5;
				return 29;
			}
			return -1;
		case 6:
			if ((active0 & 0x800L) != 0L) {
				jjmatchedKind = 16;
				jjmatchedPos = 6;
				return 29;
			}
			if ((active0 & 0x200L) != 0L) {
				if (jjmatchedPos < 2) {
					jjmatchedKind = 16;
					jjmatchedPos = 2;
				}
				return -1;
			}
			if ((active0 & 0x4c0L) != 0L) {
				if (jjmatchedPos < 1) {
					jjmatchedKind = 16;
					jjmatchedPos = 1;
				}
				return -1;
			}
			if ((active0 & 0x100L) != 0L)
				return 29;
			return -1;
		case 7:
			if ((active0 & 0x200L) != 0L) {
				if (jjmatchedPos < 2) {
					jjmatchedKind = 16;
					jjmatchedPos = 2;
				}
				return -1;
			}
			if ((active0 & 0x4c0L) != 0L) {
				if (jjmatchedPos < 1) {
					jjmatchedKind = 16;
					jjmatchedPos = 1;
				}
				return -1;
			}
			if ((active0 & 0x800L) != 0L)
				return 29;
			return -1;
		default:
			return -1;
		}
	}

	private final int jjStartNfa_0(int pos, long active0) {
		return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
	}

	private final int jjStopAtPos(int pos, int kind) {
		jjmatchedKind = kind;
		jjmatchedPos = pos;
		return pos + 1;
	}

	private final int jjStartNfaWithStates_0(int pos, int kind, int state) {
		jjmatchedKind = kind;
		jjmatchedPos = pos;
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			return pos + 1;
		}
		return jjMoveNfa_0(state, pos + 1);
	}

	private final int jjMoveStringLiteralDfa0_0() {
		switch (curChar) {
		case 10:
			return jjStopAtPos(0, 4);
		case 40:
			return jjStopAtPos(0, 20);
		case 41:
			return jjStopAtPos(0, 22);
		case 44:
			return jjStopAtPos(0, 19);
		case 47:
			return jjStopAtPos(0, 21);
		case 67:
		case 99:
			return jjMoveStringLiteralDfa1_0(0x100L);
		case 78:
		case 110:
			return jjMoveStringLiteralDfa1_0(0x400L);
		case 79:
		case 111:
			return jjMoveStringLiteralDfa1_0(0xc0L);
		case 82:
		case 114:
			return jjMoveStringLiteralDfa1_0(0x820L);
		case 83:
		case 115:
			return jjMoveStringLiteralDfa1_0(0x200L);
		default:
			return jjMoveNfa_0(0, 0);
		}
	}

	private final int jjMoveStringLiteralDfa1_0(long active0) {
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(0, active0);
			return 1;
		}
		switch (curChar) {
		case 65:
		case 97:
			return jjMoveStringLiteralDfa2_0(active0, 0x100L);
		case 69:
		case 101:
			return jjMoveStringLiteralDfa2_0(active0, 0xa20L);
		case 78:
		case 110:
			return jjMoveStringLiteralDfa2_0(active0, 0xc0L);
		case 79:
		case 111:
			return jjMoveStringLiteralDfa2_0(active0, 0x400L);
		default:
			break;
		}
		return jjStartNfa_0(0, active0);
	}

	private final int jjMoveStringLiteralDfa2_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(0, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(1, active0);
			return 2;
		}
		switch (curChar) {
		case 32:
			return jjMoveStringLiteralDfa3_0(active0, 0x4c0L);
		case 70:
		case 102:
			return jjMoveStringLiteralDfa3_0(active0, 0x20L);
		case 83:
		case 115:
			return jjMoveStringLiteralDfa3_0(active0, 0x900L);
		case 84:
		case 116:
			return jjMoveStringLiteralDfa3_0(active0, 0x200L);
		default:
			break;
		}
		return jjStartNfa_0(1, active0);
	}

	private final int jjMoveStringLiteralDfa3_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(1, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(2, active0);
			return 3;
		}
		switch (curChar) {
		case 32:
			return jjMoveStringLiteralDfa4_0(active0, 0x200L);
		case 65:
		case 97:
			return jjMoveStringLiteralDfa4_0(active0, 0x400L);
		case 67:
		case 99:
			return jjMoveStringLiteralDfa4_0(active0, 0x100L);
		case 68:
		case 100:
			return jjMoveStringLiteralDfa4_0(active0, 0x40L);
		case 69:
		case 101:
			return jjMoveStringLiteralDfa4_0(active0, 0x20L);
		case 84:
		case 116:
			return jjMoveStringLiteralDfa4_0(active0, 0x800L);
		case 85:
		case 117:
			return jjMoveStringLiteralDfa4_0(active0, 0x80L);
		default:
			break;
		}
		return jjStartNfa_0(2, active0);
	}

	private final int jjMoveStringLiteralDfa4_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(2, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(3, active0);
			return 4;
		}
		switch (curChar) {
		case 65:
		case 97:
			return jjMoveStringLiteralDfa5_0(active0, 0x100L);
		case 67:
		case 99:
			return jjMoveStringLiteralDfa5_0(active0, 0x400L);
		case 69:
		case 101:
			return jjMoveStringLiteralDfa5_0(active0, 0x40L);
		case 78:
		case 110:
			return jjMoveStringLiteralDfa5_0(active0, 0x200L);
		case 80:
		case 112:
			return jjMoveStringLiteralDfa5_0(active0, 0x80L);
		case 82:
		case 114:
			if ((active0 & 0x20L) != 0L)
				return jjStartNfaWithStates_0(4, 5, 29);
			return jjMoveStringLiteralDfa5_0(active0, 0x800L);
		default:
			break;
		}
		return jjStartNfa_0(3, active0);
	}

	private final int jjMoveStringLiteralDfa5_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(3, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(4, active0);
			return 5;
		}
		switch (curChar) {
		case 68:
		case 100:
			return jjMoveStringLiteralDfa6_0(active0, 0x180L);
		case 73:
		case 105:
			return jjMoveStringLiteralDfa6_0(active0, 0x800L);
		case 76:
		case 108:
			return jjMoveStringLiteralDfa6_0(active0, 0x40L);
		case 84:
		case 116:
			return jjMoveStringLiteralDfa6_0(active0, 0x400L);
		case 85:
		case 117:
			return jjMoveStringLiteralDfa6_0(active0, 0x200L);
		default:
			break;
		}
		return jjStartNfa_0(4, active0);
	}

	private final int jjMoveStringLiteralDfa6_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(4, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(5, active0);
			return 6;
		}
		switch (curChar) {
		case 65:
		case 97:
			return jjMoveStringLiteralDfa7_0(active0, 0x80L);
		case 67:
		case 99:
			return jjMoveStringLiteralDfa7_0(active0, 0x800L);
		case 69:
		case 101:
			if ((active0 & 0x100L) != 0L)
				return jjStartNfaWithStates_0(6, 8, 29);
			return jjMoveStringLiteralDfa7_0(active0, 0x40L);
		case 73:
		case 105:
			return jjMoveStringLiteralDfa7_0(active0, 0x400L);
		case 76:
		case 108:
			return jjMoveStringLiteralDfa7_0(active0, 0x200L);
		default:
			break;
		}
		return jjStartNfa_0(5, active0);
	}

	private final int jjMoveStringLiteralDfa7_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(5, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(6, active0);
			return 7;
		}
		switch (curChar) {
		case 76:
		case 108:
			if ((active0 & 0x200L) != 0L)
				return jjStopAtPos(7, 9);
			break;
		case 79:
		case 111:
			return jjMoveStringLiteralDfa8_0(active0, 0x400L);
		case 84:
		case 116:
			if ((active0 & 0x800L) != 0L)
				return jjStartNfaWithStates_0(7, 11, 29);
			return jjMoveStringLiteralDfa8_0(active0, 0xc0L);
		default:
			break;
		}
		return jjStartNfa_0(6, active0);
	}

	private final int jjMoveStringLiteralDfa8_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(6, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(7, active0);
			return 8;
		}
		switch (curChar) {
		case 69:
		case 101:
			if ((active0 & 0x40L) != 0L)
				return jjStopAtPos(8, 6);
			else if ((active0 & 0x80L) != 0L)
				return jjStopAtPos(8, 7);
			break;
		case 78:
		case 110:
			if ((active0 & 0x400L) != 0L)
				return jjStopAtPos(8, 10);
			break;
		default:
			break;
		}
		return jjStartNfa_0(7, active0);
	}

	private final void jjCheckNAdd(int state) {
		if (jjrounds[state] != jjround) {
			jjstateSet[jjnewStateCnt++] = state;
			jjrounds[state] = jjround;
		}
	}

	private final void jjAddStates(int start, int end) {
		do {
			jjstateSet[jjnewStateCnt++] = jjnextStates[start];
		} while (start++ != end);
	}

	private final void jjCheckNAddTwoStates(int state1, int state2) {
		jjCheckNAdd(state1);
		jjCheckNAdd(state2);
	}

	private final void jjCheckNAddStates(int start, int end) {
		do {
			jjCheckNAdd(jjnextStates[start]);
		} while (start++ != end);
	}

	private final void jjCheckNAddStates(int start) {
		jjCheckNAdd(jjnextStates[start]);
		jjCheckNAdd(jjnextStates[start + 1]);
	}

	static final long[] jjbitVec0 = { 0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL };

	private final int jjMoveNfa_0(int startState, int curPos) {
		int[] nextStates;
		int startsAt = 0;
		jjnewStateCnt = 29;
		int i = 1;
		jjstateSet[0] = startState;
		int j, kind = 0x7fffffff;
		for (;;) {
			if (++jjround == 0x7fffffff)
				ReInitRounds();
			if (curChar < 64) {
				long l = 1L << curChar;
				MatchLoop: do {
					switch (jjstateSet[--i]) {
					case 29:
					case 12:
						if ((0x3ff001800000000L & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjCheckNAdd(12);
						break;
					case 0:
						if ((0x3ff000000000000L & l) != 0L) {
							if (kind > 12)
								kind = 12;
							jjCheckNAddStates(0, 6);
						} else if (curChar == 39)
							jjCheckNAddStates(7, 9);
						else if (curChar == 46)
							jjCheckNAdd(1);
						break;
					case 1:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 13)
							kind = 13;
						jjCheckNAddTwoStates(1, 2);
						break;
					case 3:
						if ((0x280000000000L & l) != 0L)
							jjCheckNAdd(4);
						break;
					case 4:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 13)
							kind = 13;
						jjCheckNAdd(4);
						break;
					case 5:
						if (curChar == 39)
							jjCheckNAddStates(7, 9);
						break;
					case 6:
						if ((0xffffff7fffffffffL & l) != 0L)
							jjCheckNAddStates(7, 9);
						break;
					case 7:
						if (curChar == 39)
							jjCheckNAddStates(10, 12);
						break;
					case 8:
						if (curChar == 39)
							jjstateSet[jjnewStateCnt++] = 7;
						break;
					case 9:
						if ((0xffffff7fffffffffL & l) != 0L)
							jjCheckNAddStates(10, 12);
						break;
					case 10:
						if (curChar == 39 && kind > 15)
							kind = 15;
						break;
					case 13:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 12)
							kind = 12;
						jjCheckNAddStates(0, 6);
						break;
					case 14:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 12)
							kind = 12;
						jjCheckNAdd(14);
						break;
					case 15:
						if ((0x3ff000000000000L & l) != 0L)
							jjCheckNAddTwoStates(15, 16);
						break;
					case 16:
						if (curChar == 46)
							jjCheckNAdd(17);
						break;
					case 17:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 13)
							kind = 13;
						jjCheckNAddTwoStates(17, 18);
						break;
					case 19:
						if ((0x280000000000L & l) != 0L)
							jjCheckNAdd(20);
						break;
					case 20:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 13)
							kind = 13;
						jjCheckNAdd(20);
						break;
					case 21:
						if ((0x3ff000000000000L & l) != 0L)
							jjCheckNAddTwoStates(21, 22);
						break;
					case 23:
						if ((0x280000000000L & l) != 0L)
							jjCheckNAdd(24);
						break;
					case 24:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 13)
							kind = 13;
						jjCheckNAdd(24);
						break;
					case 25:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 13)
							kind = 13;
						jjCheckNAddTwoStates(25, 26);
						break;
					case 27:
						if ((0x280000000000L & l) != 0L)
							jjCheckNAdd(28);
						break;
					case 28:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 13)
							kind = 13;
						jjCheckNAdd(28);
						break;
					default:
						break;
					}
				} while (i != startsAt);
			} else if (curChar < 128) {
				long l = 1L << (curChar & 077);
				MatchLoop: do {
					switch (jjstateSet[--i]) {
					case 29:
						if ((0x7fffffe87fffffeL & l) != 0L) {
							if (kind > 16)
								kind = 16;
							jjCheckNAdd(12);
						}
						if ((0x7fffffe07fffffeL & l) != 0L) {
							if (kind > 16)
								kind = 16;
							jjCheckNAddTwoStates(11, 12);
						}
						break;
					case 0:
					case 11:
						if ((0x7fffffe07fffffeL & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjCheckNAddTwoStates(11, 12);
						break;
					case 2:
						if ((0x2000000020L & l) != 0L)
							jjAddStates(13, 14);
						break;
					case 6:
						jjCheckNAddStates(7, 9);
						break;
					case 9:
						jjCheckNAddStates(10, 12);
						break;
					case 12:
						if ((0x7fffffe87fffffeL & l) == 0L)
							break;
						if (kind > 16)
							kind = 16;
						jjCheckNAdd(12);
						break;
					case 18:
						if ((0x2000000020L & l) != 0L)
							jjAddStates(15, 16);
						break;
					case 22:
						if ((0x2000000020L & l) != 0L)
							jjAddStates(17, 18);
						break;
					case 26:
						if ((0x2000000020L & l) != 0L)
							jjAddStates(19, 20);
						break;
					default:
						break;
					}
				} while (i != startsAt);
			} else {
				int i2 = (curChar & 0xff) >> 6;
				long l2 = 1L << (curChar & 077);
				MatchLoop: do {
					switch (jjstateSet[--i]) {
					case 6:
						if ((jjbitVec0[i2] & l2) != 0L)
							jjCheckNAddStates(7, 9);
						break;
					case 9:
						if ((jjbitVec0[i2] & l2) != 0L)
							jjCheckNAddStates(10, 12);
						break;
					default:
						break;
					}
				} while (i != startsAt);
			}
			if (kind != 0x7fffffff) {
				jjmatchedKind = kind;
				jjmatchedPos = curPos;
				kind = 0x7fffffff;
			}
			++curPos;
			if ((i = jjnewStateCnt) == (startsAt = 29 - (jjnewStateCnt = startsAt)))
				return curPos;
			try {
				curChar = input_stream.readChar();
			} catch (java.io.IOException e) {
				return curPos;
			}
		}
	}

	static final int[] jjnextStates = { 14, 15, 16, 21, 22, 25, 26, 6, 8, 10, 8, 9, 10, 3, 4, 19, 20, 23, 24, 27, 28, };
	public static final String[] jjstrLiteralImages = { "", null, null, null, "\12", null, null, null, null, null,
			null, null, null, null, null, null, null, null, null, "\54", "\50", "\57", "\51", };
	public static final String[] lexStateNames = { "DEFAULT", };
	static final long[] jjtoToken = { 0x79bff1L, };
	static final long[] jjtoSkip = { 0xeL, };
	private SimpleCharStream input_stream;
	private final int[] jjrounds = new int[29];
	private final int[] jjstateSet = new int[58];
	protected char curChar;

	public MySQLForeignKeyParserTokenManager(SimpleCharStream stream) {
		if (SimpleCharStream.staticFlag)
			throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
		input_stream = stream;
	}

	public MySQLForeignKeyParserTokenManager(SimpleCharStream stream, int lexState) {
		this(stream);
		SwitchTo(lexState);
	}

	public void ReInit(SimpleCharStream stream) {
		jjmatchedPos = jjnewStateCnt = 0;
		curLexState = defaultLexState;
		input_stream = stream;
		ReInitRounds();
	}

	private final void ReInitRounds() {
		int i;
		jjround = 0x80000001;
		for (i = 29; i-- > 0;)
			jjrounds[i] = 0x80000000;
	}

	public void ReInit(SimpleCharStream stream, int lexState) {
		ReInit(stream);
		SwitchTo(lexState);
	}

	public void SwitchTo(int lexState) {
		if (lexState >= 1 || lexState < 0)
			throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
					TokenMgrError.INVALID_LEXICAL_STATE);
		else
			curLexState = lexState;
	}

	private final Token jjFillToken() {
		Token t = Token.newToken(jjmatchedKind);
		t.kind = jjmatchedKind;
		String im = jjstrLiteralImages[jjmatchedKind];
		t.image = (im == null) ? input_stream.GetImage() : im;
		t.beginLine = input_stream.getBeginLine();
		t.beginColumn = input_stream.getBeginColumn();
		t.endLine = input_stream.getEndLine();
		t.endColumn = input_stream.getEndColumn();
		return t;
	}

	int curLexState = 0;
	int defaultLexState = 0;
	int jjnewStateCnt;
	int jjround;
	int jjmatchedPos;
	int jjmatchedKind;

	public final Token getNextToken() {
		int kind;
		Token specialToken = null;
		Token matchedToken;
		int curPos = 0;

		EOFLoop: for (;;) {
			try {
				curChar = input_stream.BeginToken();
			} catch (java.io.IOException e) {
				jjmatchedKind = 0;
				matchedToken = jjFillToken();
				return matchedToken;
			}

			try {
				input_stream.backup(0);
				while (curChar <= 32 && (0x100002200L & (1L << curChar)) != 0L)
					curChar = input_stream.BeginToken();
			} catch (java.io.IOException e1) {
				continue EOFLoop;
			}
			jjmatchedKind = 0x7fffffff;
			jjmatchedPos = 0;
			curPos = jjMoveStringLiteralDfa0_0();
			if (jjmatchedKind != 0x7fffffff) {
				if (jjmatchedPos + 1 < curPos)
					input_stream.backup(curPos - jjmatchedPos - 1);
				if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
					matchedToken = jjFillToken();
					return matchedToken;
				} else {
					continue EOFLoop;
				}
			}
			int error_line = input_stream.getEndLine();
			int error_column = input_stream.getEndColumn();
			String error_after = null;
			boolean EOFSeen = false;
			try {
				input_stream.readChar();
				input_stream.backup(1);
			} catch (java.io.IOException e1) {
				EOFSeen = true;
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
				if (curChar == '\n' || curChar == '\r') {
					error_line++;
					error_column = 0;
				} else
					error_column++;
			}
			if (!EOFSeen) {
				input_stream.backup(1);
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
			}
			throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar,
					TokenMgrError.LEXICAL_ERROR);
		}
	}

}
