/* Generated By:JavaCC: Do not edit this line. MySQLForeignKeyParserConstants.java */
package com.jeta.plugins.abeille.mysql.parsers;

public interface MySQLForeignKeyParserConstants {

	int EOF = 0;
	int EOL = 4;
	int REFER = 5;
	int ON_DELETE = 6;
	int ON_UPDATE = 7;
	int CASCADE = 8;
	int SET_NULL = 9;
	int NO_ACTION = 10;
	int RESTRICT = 11;
	int INTEGER_LITERAL = 12;
	int FLOATING_POINT_LITERAL = 13;
	int EXPONENT = 14;
	int STRING_LITERAL = 15;
	int ID = 16;
	int LETTER = 17;
	int DIGIT = 18;
	int COMMA = 19;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"", "\"REFER\"", "\"ON DELETE\"",
			"\"ON UPDATE\"", "\"CASCADE\"", "\"SET NULL\"", "\"NO ACTION\"", "\"RESTRICT\"", "<INTEGER_LITERAL>",
			"<FLOATING_POINT_LITERAL>", "<EXPONENT>", "<STRING_LITERAL>", "<ID>", "<LETTER>", "<DIGIT>", "\",\"",
			"\"(\"", "\"/\"", "\")\"", };

}
